# Site settings
title: Pyladies Mendoza 
email: "mendoza@pyladies.com" 
description: PyLadies is an international group mentoring focused on helping more and more women to become active participants and leaders in the open-source Python community.
url: "http://pyladiesmdz.github.io"
# baseurl: "/pyladiesmdz"
# twitter_username: pyladiesmdz
github_username: pyladiesmdz

# Build settings
markdown: kramdown

highlighter: blue

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"

collections:
  home:
    output: true
    permalink: /home/:path/
  home-es:
    output: true
    permalink: /home-es/:path/
  ladies:
    output: true
    permalink: /ladies/:path/
  events:
    output: true
    permalink: /events/:path/
  jobs:
    output: true
    permalink: /jobs/:path/
