# Site settings
title: Pyladies Mendoza
email: mendoza@pyladies.com
description: > # this means to ignore newlines until "baseurl:"
 PyLadies is an international group mentoring focused on helping more and more women to become active participants and leaders in the open-source Python community.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: pyladies_mendoza
github_username:  PyladiesMendoza

# Build settings
markdown: kramdown

highlighter: blue

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"

collections:
  home-es:
    output: true
    permalink: /home-es/:path/
  ladies:
    output: true
    permalink: /ladies/:path/
  events:
    output: true
    permalink: /events/:path/